### ISSUE TITLE
The site size equal to 0M returned

### ISSUE THREAD

**Issue by diglan** [izkreny/website-size#1]
I've given an attempt to obtain full size of site and unfortunately absolutely always get zero megabytes.
It's seen on terminal session given below:

<pre>
$ website-size -r -l 10 https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/ObjC_classic/
### This will take some time to finish, please wait. ###
Finished with crawling!
Estimated size: 0 Mb
</pre>

**Comment by andypillip** [comment]
I just tried several scripts, this one among them, and have the same issue.
Maybe `wget` changed its behaviour?

When checking the logfile, I notice that none of the header blocks is for a `Content-type: image…`. 

For CSS files, length is returned by wget, but the script seems to fail to sum them up.

When it comes to images (which I’m interested in), the logfile contains tons of lines like this, but no headers.

    [2] Checking 'https://…d6a21343d3.jpg' ...
    HTTP response 200  [https://…7bd7641474.jpg]

**Comment by izkreny** [comment]
Hey @andypillip!

I created this script a long time ago and haven't used it by myself for ages as well. But I'm also curious about what's happening, so I will look at it next week for sure!

#keepintouch

**Comment by izkreny** [comment]
Hi @andypillip and @diglan. I have just checked and, although this BASH code is more than 10 years old and really raw and simple, it seems that scripts are working just fine on some simple websites. On some sites it will not work for sure as it could be recognized as a sniffer -- which it is, to be honest. :)

I'm not able to help you further without the exact steps to reproduce your issue, so I guess that playing with `--wait` and `--user-agent` wget options could **MAYBE** trick sites/servers that are not cooperating and that don't provide complete information inside the HTTP headers.
